---
name: Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  frontend-ci:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write  
    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{github.head_ref}}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          always-auth: true
          scope: '@schubergphilis'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Setup git user"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          
      - name: Install dependencies
        working-directory: sbp-frontend-style
        run: yarn install
            
      - name: Build component list
        working-directory: sbp-frontend-style
        run: yarn prebuild

      - name: Run Tests
        working-directory: sbp-frontend-style
        run: yarn test

      - name: Build project
        working-directory: sbp-frontend-style
        run: yarn build
        env:
          GENERATE_SOURCEMAP: "false"
      
      - name: Create release version
        working-directory: sbp-frontend-style
        run: yarn version --minor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Package project
        working-directory: sbp-frontend-style
        run: yarn pack && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check-in new version
        run: |
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push

      - name: Extract version from package.json
        id: pkg
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          tag: v${{ steps.pkg.outputs.version }}
          name: v${{ steps.pkg.outputs.version }}
          version: ${{ steps.pkg.outputs.version }}
          publish: true
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

