---
name: Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  frontend-ci:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          always-auth: true
          scope: '@schubergphilis'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install dependencies
        working-directory: frontend-shared-components
        run: yarn install

      - name: Run Tests
        working-directory: frontend-shared-components
        run: yarn test

      - name: Build project
        working-directory: frontend-shared-components
        run: yarn build
        env:
          GENERATE_SOURCEMAP: "false"
      
      - name: Create release version
        working-directory: frontend-shared-components
        run: yarn version --minor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Package project
        working-directory: frontend-shared-components
        run: yarn pack && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      
      - name: "Setup git user"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Check-in new version
        run: |
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push
