---
name: Package Pre-release CI

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  frontend-ci:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}} 

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          always-auth: true
          scope: '@schubergphilis'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup git user"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Install dependencies
        working-directory: sbp-frontend-style
        run: yarn install

      - name: Build component list
        working-directory: sbp-frontend-style
        run: yarn prebuild

      - name: Run Tests
        working-directory: sbp-frontend-style
        run: yarn test  

      - name: Build project
        working-directory: sbp-frontend-style
        run: yarn build
        env:
          GENERATE_SOURCEMAP: "false"

      - name: Create pre-release version
        working-directory: sbp-frontend-style
        run: yarn version --prerelease --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Package project
        working-directory: sbp-frontend-style
        run: yarn pack && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check-in new version
        run: |
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push


